### ISSUE TITLE
Support own names for `g` / `m`

### ISSUE THREAD

**Issue by matthiasbeyer** [charles-l/shmark#1]
I'd like to have other names then `g` and `m` for the functions.

I could implement such a thing, if you want me to!

---

I don't want to hack it into the application, because I'd like to package it for my distribution and it should be a configureable without hacking in the source directly then.

**Comment by charles-l** [comment]
@matthiasbeyer sure! I'll add an rc file that allows you to set the names of the functions.

**Comment by matthiasbeyer** [comment]
:+1:

**Comment by charles-l** [comment]
I don't really think the few extra lines add too much functionality, so I'm currently just keeping this feature [as a separate branch](https://github.com/charles-l/shmark/tree/rc). Just add `source shmark.sh` to the `.profile`, drop `.shmarkrc` into your home directory and you should be good to go :)
